// Auto-generated by scripts/split-knowledge-base.mjs
// Source: src/data/knowledge-base.json

import angular from './angular.json';
import ansible from './ansible.json';
import api from './api.json';
import ciCd from './ci-cd.json';
import database from './database.json';
import dddTddBdd from './ddd-tdd-bdd.json';
import designPattern from './design-pattern.json';
import git from './git.json';
import htmlCss from './html-css.json';
import http from './http.json';
import httpProtocols from './http-protocols.json';
import java from './java.json';
import javascript from './javascript.json';
import markdown from './markdown.json';
import nodeJs from './node-js.json';
import python from './python.json';
import react from './react.json';
import restApi from './rest-api.json';
import server from './server.json';
import terraform from './terraform.json';
import uncategorized from './uncategorized.json';

export const byMainTopic = {
  "Angular": angular,
  "Ansible": ansible,
  "API": api,
  "CI/CD": ciCd,
  "Database": database,
  "DDD, TDD, BDD": dddTddBdd,
  "Design Pattern": designPattern,
  "Git": git,
  "HTML/CSS": htmlCss,
  "HTTP": http,
  "HTTP Protocols": httpProtocols,
  "Java": java,
  "Javascript": javascript,
  "Markdown": markdown,
  "Node.js": nodeJs,
  "Python": python,
  "React": react,
  "REST API": restApi,
  "Server": server,
  "Terraform": terraform,
  "Uncategorized": uncategorized,
} as const;

export const mainTopics = Object.keys(byMainTopic).sort((a, b) =>
  a.localeCompare(b, undefined, { sensitivity: 'base' })
);

const all = Object.values(byMainTopic).flat();
export default all;
